**Data Wrangling in Pandas**

https://pandas.pydata.org/docs/index.html

With the basis on:

https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html

Check the official Pandas Cheat Sheet:

https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [1]:
import pandas as pd

us_statistics = pd.read_excel("C:/Users/artem/Desktop/Data Science/US Statistics.xlsx")

#Note that we are using pd.read_excel() instead of pd.read_csv() here

us_statistics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year                               35 non-null     int64
 1   Unadjusted Business Profits        35 non-null     float64
 2   Unadjusted Depreciation Estimates  35 non-null     float64
 3   Adjusted Business Profits          35 non-null     float64
 4   Adjusted Depreciation Estimates    35 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 1.5 KB

In [2]:
us_statistics.head()

,Year,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates
0,1929,14.180,6.627,17.251,3.556
1,1930,9.252,6.660,12.334,3.578
2,1931,2.284,6.493,5.295,3.482
3,1932,-3.177,5.995,-0.399,3.217
4,1933,-3.310,5.612,-0.709,3.011

In [3]:
us_statistics.tail()

,Year,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates
30,1959,40.686,32.131,58.895,13.922
31,1960,37.653,33.577,57.066,14.164
32,1961,37.374,34.740,57.758,14.356
33,1962,41.595,38.366,64.089,15.872
34,1963,42.929,40.009,66.558,16.380

In [4]:
type(us_statistics["Unadjusted Business Profits"])

pandas.core.series.Series

In [5]:
us_statistics["Unadjusted Business Profits"].shape

(35,)

In [6]:
type(us_statistics[["Year", "Unadjusted Business Profits"]])

pandas.core.frame.DataFrame

In [7]:
us_statistics[["Year", "Unadjusted Business Profits"]].shape

(35, 2)

In [8]:
#Subsetting

unadjusted_business_profits = us_statistics["Unadjusted Business Profits"]

unadjusted_business_profits.head()

0    14.180
1     9.252
2     2.284
3    -3.177
4    -3.310
Name: Unadjusted Business Profits, dtype: float64

In [9]:
#Performing a categorization (boolean outcome)

us_statistics["Unadjusted Business Profits"] < 0

0     False
1     False
2     False
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
Name: Unadjusted Business Profits, dtype: bool

In [10]:
#Performing a filtered selection (any given outcome)

us_statistics[us_statistics["Unadjusted Business Profits"] < 0]

,Year,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates
3,1932,-3.177,5.995,-0.399,3.217
4,1933,-3.310,5.612,-0.709,3.011

In [11]:
#Performing a filtered multiple selection

us_statistics[(us_statistics["Year"] >= 1929) & (us_statistics["Year"] <= 1939)]

,Year,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates
0,1929,14.180,6.627,17.251,3.556
1,1930,9.252,6.660,12.334,3.578
2,1931,2.284,6.493,5.295,3.482
3,1932,-3.177,5.995,-0.399,3.217
4,1933,-3.310,5.612,-0.709,3.011
5,1934,1.258,5.531,3.822,2.967
6,1935,4.096,5.593,6.685,3.004
7,1936,6.550,5.616,9.148,3.018
8,1937,8.293,5.811,10.983,3.121
9,1938,5.869,5.836,8.569,3.136
10,1939,7.429,6.004,10.208,3.225

In [12]:
us_statistics.loc[(us_statistics["Year"] >= 1929) & (us_statistics["Year"] <= 1939)]

#This can be done equivalently using the loc operator

,Year,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates
0,1929,14.180,6.627,17.251,3.556
1,1930,9.252,6.660,12.334,3.578
2,1931,2.284,6.493,5.295,3.482
3,1932,-3.177,5.995,-0.399,3.217
4,1933,-3.310,5.612,-0.709,3.011
5,1934,1.258,5.531,3.822,2.967
6,1935,4.096,5.593,6.685,3.004
7,1936,6.550,5.616,9.148,3.018
8,1937,8.293,5.811,10.983,3.121
9,1938,5.869,5.836,8.569,3.136
10,1939,7.429,6.004,10.208,3.225

In [13]:
#Performing a filtered multiple selection using the iloc operator

us_statistics.iloc[0:11]

#REMINDER:

#We use loc for label-based filtering (using row/column names)

#We use iloc for position-based filtering (using table positions)

,Year,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates
0,1929,14.180,6.627,17.251,3.556
1,1930,9.252,6.660,12.334,3.578
2,1931,2.284,6.493,5.295,3.482
3,1932,-3.177,5.995,-0.399,3.217
4,1933,-3.310,5.612,-0.709,3.011
5,1934,1.258,5.531,3.822,2.967
6,1935,4.096,5.593,6.685,3.004
7,1936,6.550,5.616,9.148,3.018
8,1937,8.293,5.811,10.983,3.121
9,1938,5.869,5.836,8.569,3.136
10,1939,7.429,6.004,10.208,3.225

In [14]:
#Creating a new variable derived from the information contained in the previously existing variables

us_statistics["Net Economic Surplus"] = (
    us_statistics["Adjusted Business Profits"] - us_statistics["Adjusted Depreciation Estimates"]
)

us_statistics.info()
us_statistics.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year                               35 non-null     int64
 1   Unadjusted Business Profits        35 non-null     float64
 2   Unadjusted Depreciation Estimates  35 non-null     float64
 3   Adjusted Business Profits          35 non-null     float64
 4   Adjusted Depreciation Estimates    35 non-null     float64
 5   Net Economic Surplus               35 non-null     float64
dtypes: float64(5), int64(1)
memory usage: 1.8 KB

,Year,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates,Net Economic Surplus
0,1929,14.180,6.627,17.251,3.556,13.695
1,1930,9.252,6.660,12.334,3.578,8.756
2,1931,2.284,6.493,5.295,3.482,1.813
3,1932,-3.177,5.995,-0.399,3.217,-3.616
4,1933,-3.310,5.612,-0.709,3.011,-3.720

In [15]:
#Renaming a column

us_statistics = us_statistics.rename(
    columns={
        "Year": "Year of Data Analysis"
    }
)

us_statistics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year of Data Analysis              35 non-null     int64
 1   Unadjusted Business Profits        35 non-null     float64
 2   Unadjusted Depreciation Estimates  35 non-null     float64
 3   Adjusted Business Profits          35 non-null     float64
 4   Adjusted Depreciation Estimates    35 non-null     float64
 5   Net Economic Surplus               35 non-null     float64
dtypes: float64(5), int64(1)
memory usage: 1.8 KB

In [16]:
#Calculating the mean

us_statistics["Net Economic Surplus"].mean()

np.float64(22.730428571428572)

In [17]:
#Calculating the median

us_statistics["Net Economic Surplus"].median()

21.116

In [18]:
#Calculating aggregate statistics

us_statistics.describe()

,Year of Data Analysis,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates,Net Economic Surplus
count,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000
mean,1946.000000,22.181486,15.272971,30.092429,7.362000,22.730429
std,10.246951,14.413577,11.158541,20.130741,4.590121,15.838768
min,1929.000000,-3.310000,5.531000,-0.709000,2.967000,-3.720000
25%,1937.500000,8.772500,6.331500,11.658500,3.397500,8.309000
50%,1946.000000,21.810000,9.334000,26.130000,5.014000,21.116000
75%,1954.500000,34.983000,23.089000,46.689000,11.724000,35.568500
max,1963.000000,42.929000,40.009000,66.558000,16.380000,50.178000

In [19]:
#Sorting the data in ascending order by Unadjusted Business Profits

us_statistics.sort_values(by="Unadjusted Business Profits").head()

,Year of Data Analysis,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates,Net Economic Surplus
4,1933,-3.310,5.612,-0.709,3.011,-3.720
3,1932,-3.177,5.995,-0.399,3.217,-3.616
5,1934,1.258,5.531,3.822,2.967,0.855
2,1931,2.284,6.493,5.295,3.482,1.813
6,1935,4.096,5.593,6.685,3.004,3.681

In [20]:
#Sorting the data in descending order by Unadjusted Business Profits

us_statistics.sort_values(by="Unadjusted Business Profits", ascending=False).head()

,Year of Data Analysis,Unadjusted Business Profits,Unadjusted Depreciation Estimates,Adjusted Business Profits,Adjusted Depreciation Estimates,Net Economic Surplus
34,1963,42.929,40.009,66.558,16.380,50.178
33,1962,41.595,38.366,64.089,15.872,48.217
30,1959,40.686,32.131,58.895,13.922,44.973
31,1960,37.653,33.577,57.066,14.164,42.902
26,1955,37.550,24.290,49.818,12.022,37.796

In [21]:
#Wide to long format (using .melt)

us_statistics_long = us_statistics.melt(
    value_vars=["Unadjusted Business Profits", "Unadjusted Depreciation Estimates"],
    var_name="Component",
    value_name="Value",
)

us_statistics_long.info()
us_statistics_long.head()

#We use .pivot for long to wide transformation

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Component  70 non-null     object
 1   Value      70 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.2+ KB

                     Component   Value
0  Unadjusted Business Profits  14.180
1  Unadjusted Business Profits   9.252
2  Unadjusted Business Profits   2.284
3  Unadjusted Business Profits  -3.177
4  Unadjusted Business Profits  -3.310

Joining data from across multiple tables:

https://pandas.pydata.org/docs/getting_started/intro_tutorials/08_combine_dataframes.html