**Data Wrangling in Polars**

https://docs.pola.rs/

With the basis on:

https://docs.pola.rs/user-guide/getting-started/

https://occasionaldivergences.com/posts/python-intro/

Check the Polars Cheat Sheet:

https://franzdiebold.github.io/polars-cheat-sheet/Polars_cheat_sheet.pdf

In [1]:
#pip install polars
#pip install fastexcel

import polars as pl

us_statistics = pl.read_excel("C:/Users/artem/Desktop/Data Science/US Statistics.xlsx")

#Note that we are using pd.read_excel() instead of pd.read_csv() here

print(us_statistics)

shape: (35, 5)
┌──────┬───────────────────────┬───────────────────────┬───────────────────┬───────────────────────┐
│ Year ┆ Unadjusted Business   ┆ Unadjusted            ┆ Adjusted Business ┆ Adjusted Depreciation │
│ ---  ┆ Profits               ┆ Depreciation Estima…  ┆ Profits           ┆ Estimate…             │
│ i64  ┆ ---                   ┆ ---                   ┆ ---               ┆ ---                   │
│      ┆ f64                   ┆ f64                   ┆ f64               ┆ f64                   │
╞══════╪═══════════════════════╪═══════════════════════╪═══════════════════╪═══════════════════════╡
│ 1929 ┆ 14.18                 ┆ 6.627                 ┆ 17.251            ┆ 3.556                 │
│ 1930 ┆ 9.252                 ┆ 6.66                  ┆ 12.334            ┆ 3.578                 │
│ 1931 ┆ 2.284                 ┆ 6.493                 ┆ 5.295             ┆ 3.482                 │
│ 1932 ┆ -3.177                ┆ 5.995                 ┆ -0.399            ┆ 3.217                 │
│ 1933 ┆ -3.31                 ┆ 5.612                 ┆ -0.709            ┆ 3.011                 │
│ …    ┆ …                     ┆ …                     ┆ …                 ┆ …                     │
│ 1959 ┆ 40.686                ┆ 32.131                ┆ 58.895            ┆ 13.922                │
│ 1960 ┆ 37.653                ┆ 33.577                ┆ 57.066            ┆ 14.164                │
│ 1961 ┆ 37.374                ┆ 34.74                 ┆ 57.758            ┆ 14.356                │
│ 1962 ┆ 41.595                ┆ 38.366                ┆ 64.089            ┆ 15.872                │
│ 1963 ┆ 42.929                ┆ 40.009                ┆ 66.558            ┆ 16.38                 │
└──────┴───────────────────────┴───────────────────────┴───────────────────┴───────────────────────┘

In [2]:
us_statistics.head()

shape: (5, 5)
┌──────┬───────────────────────┬───────────────────────┬───────────────────┬───────────────────────┐
│ Year ┆ Unadjusted Business   ┆ Unadjusted            ┆ Adjusted Business ┆ Adjusted Depreciation │
│ ---  ┆ Profits               ┆ Depreciation Estima…  ┆ Profits           ┆ Estimate…             │
│ i64  ┆ ---                   ┆ ---                   ┆ ---               ┆ ---                   │
│      ┆ f64                   ┆ f64                   ┆ f64               ┆ f64                   │
╞══════╪═══════════════════════╪═══════════════════════╪═══════════════════╪═══════════════════════╡
│ 1929 ┆ 14.18                 ┆ 6.627                 ┆ 17.251            ┆ 3.556                 │
│ 1930 ┆ 9.252                 ┆ 6.66                  ┆ 12.334            ┆ 3.578                 │
│ 1931 ┆ 2.284                 ┆ 6.493                 ┆ 5.295             ┆ 3.482                 │
│ 1932 ┆ -3.177                ┆ 5.995                 ┆ -0.399            ┆ 3.217                 │
│ 1933 ┆ -3.31                 ┆ 5.612                 ┆ -0.709            ┆ 3.011                 │
└──────┴───────────────────────┴───────────────────────┴───────────────────┴───────────────────────┘

In [3]:
us_statistics.tail()

shape: (5, 5)
┌──────┬───────────────────────┬───────────────────────┬───────────────────┬───────────────────────┐
│ Year ┆ Unadjusted Business   ┆ Unadjusted            ┆ Adjusted Business ┆ Adjusted Depreciation │
│ ---  ┆ Profits               ┆ Depreciation Estima…  ┆ Profits           ┆ Estimate…             │
│ i64  ┆ ---                   ┆ ---                   ┆ ---               ┆ ---                   │
│      ┆ f64                   ┆ f64                   ┆ f64               ┆ f64                   │
╞══════╪═══════════════════════╪═══════════════════════╪═══════════════════╪═══════════════════════╡
│ 1959 ┆ 40.686                ┆ 32.131                ┆ 58.895            ┆ 13.922                │
│ 1960 ┆ 37.653                ┆ 33.577                ┆ 57.066            ┆ 14.164                │
│ 1961 ┆ 37.374                ┆ 34.74                 ┆ 57.758            ┆ 14.356                │
│ 1962 ┆ 41.595                ┆ 38.366                ┆ 64.089            ┆ 15.872                │
│ 1963 ┆ 42.929                ┆ 40.009                ┆ 66.558            ┆ 16.38                 │
└──────┴───────────────────────┴───────────────────────┴───────────────────┴───────────────────────┘

In [4]:
us_statistics.get_column("Unadjusted Business Profits").shape

(35,)

In [5]:
#Note that the previous code was a Polars equivalent to Pandas
#However, putting it simply as if we writing it in Pandas also does the job
#To better explore Polars, we will stick to Polars notation

us_statistics["Unadjusted Business Profits"].shape

(35,)

In [6]:
type(us_statistics.select("Year", "Unadjusted Business Profits"))

polars.dataframe.frame.DataFrame

In [7]:
us_statistics.select("Year", "Unadjusted Business Profits").shape

(35, 2)

In [8]:
unadjusted_business_profits = us_statistics.get_column("Unadjusted Business Profits")
unadjusted_business_profits.head()

shape: (10,)
Series: 'Unadjusted Business Profits' [f64]
[
	14.18
	9.252
	2.284
	-3.177
	-3.31
	1.258
	4.096
	6.55
	8.293
	5.869
]

In [9]:
#Performing a categorization (boolean outcome)

us_statistics.get_column("Unadjusted Business Profits") < 0

shape: (35,)
Series: 'Unadjusted Business Profits' [bool]
[
	false
	false
	false
	true
	true
	…
	false
	false
	false
	false
	false
]

In [10]:
#Performing a filtered selection (any given outcome)

us_statistics.filter(pl.col("Unadjusted Business Profits") < 0)

shape: (2, 5)
┌──────┬───────────────────────┬───────────────────────┬───────────────────┬───────────────────────┐
│ Year ┆ Unadjusted Business   ┆ Unadjusted            ┆ Adjusted Business ┆ Adjusted Depreciation │
│ ---  ┆ Profits               ┆ Depreciation Estima…  ┆ Profits           ┆ Estimate…             │
│ i64  ┆ ---                   ┆ ---                   ┆ ---               ┆ ---                   │
│      ┆ f64                   ┆ f64                   ┆ f64               ┆ f64                   │
╞══════╪═══════════════════════╪═══════════════════════╪═══════════════════╪═══════════════════════╡
│ 1932 ┆ -3.177                ┆ 5.995                 ┆ -0.399            ┆ 3.217                 │
│ 1933 ┆ -3.31                 ┆ 5.612                 ┆ -0.709            ┆ 3.011                 │
└──────┴───────────────────────┴───────────────────────┴───────────────────┴───────────────────────┘

In [11]:
#Performing a filtered multiple selection

us_statistics.filter(
(pl.col("Year") >= 1929) & (pl.col("Year") <= 1939))

#Filter is the Polars equivalent to .loc / .iloc in Pandas

shape: (11, 5)
┌──────┬───────────────────────┬───────────────────────┬───────────────────┬───────────────────────┐
│ Year ┆ Unadjusted Business   ┆ Unadjusted            ┆ Adjusted Business ┆ Adjusted Depreciation │
│ ---  ┆ Profits               ┆ Depreciation Estima…  ┆ Profits           ┆ Estimate…             │
│ i64  ┆ ---                   ┆ ---                   ┆ ---               ┆ ---                   │
│      ┆ f64                   ┆ f64                   ┆ f64               ┆ f64                   │
╞══════╪═══════════════════════╪═══════════════════════╪═══════════════════╪═══════════════════════╡
│ 1929 ┆ 14.18                 ┆ 6.627                 ┆ 17.251            ┆ 3.556                 │
│ 1930 ┆ 9.252                 ┆ 6.66                  ┆ 12.334            ┆ 3.578                 │
│ 1931 ┆ 2.284                 ┆ 6.493                 ┆ 5.295             ┆ 3.482                 │
│ 1932 ┆ -3.177                ┆ 5.995                 ┆ -0.399            ┆ 3.217                 │
│ 1933 ┆ -3.31                 ┆ 5.612                 ┆ -0.709            ┆ 3.011                 │
│ …    ┆ …                     ┆ …                     ┆ …                 ┆ …                     │
│ 1935 ┆ 4.096                 ┆ 5.593                 ┆ 6.685             ┆ 3.004                 │
│ 1936 ┆ 6.55                  ┆ 5.616                 ┆ 9.148             ┆ 3.018                 │
│ 1937 ┆ 8.293                 ┆ 5.811                 ┆ 10.983            ┆ 3.121                 │
│ 1938 ┆ 5.869                 ┆ 5.836                 ┆ 8.569             ┆ 3.136                 │
│ 1939 ┆ 7.429                 ┆ 6.004                 ┆ 10.208            ┆ 3.225                 │
└──────┴───────────────────────┴───────────────────────┴───────────────────┴───────────────────────┘

In [12]:
#Performing a multiple selection (without filtering)

us_statistics.select(pl.col(["Year", "Unadjusted Business Profits", "Unadjusted Depreciation Estimates"]))

shape: (35, 3)
┌──────┬─────────────────────────────┬─────────────────────────────────┐
│ Year ┆ Unadjusted Business Profits ┆ Unadjusted Depreciation Estima… │
│ ---  ┆ ---                         ┆ ---                             │
│ i64  ┆ f64                         ┆ f64                             │
╞══════╪═════════════════════════════╪═════════════════════════════════╡
│ 1929 ┆ 14.18                       ┆ 6.627                           │
│ 1930 ┆ 9.252                       ┆ 6.66                            │
│ 1931 ┆ 2.284                       ┆ 6.493                           │
│ 1932 ┆ -3.177                      ┆ 5.995                           │
│ 1933 ┆ -3.31                       ┆ 5.612                           │
│ …    ┆ …                           ┆ …                               │
│ 1959 ┆ 40.686                      ┆ 32.131                          │
│ 1960 ┆ 37.653                      ┆ 33.577                          │
│ 1961 ┆ 37.374                      ┆ 34.74                           │
│ 1962 ┆ 41.595                      ┆ 38.366                          │
│ 1963 ┆ 42.929                      ┆ 40.009                          │
└──────┴─────────────────────────────┴─────────────────────────────────┘

In [13]:
#Indexing data

us_statistics.slice(0, 11)

shape: (11, 5)
┌──────┬───────────────────────┬───────────────────────┬───────────────────┬───────────────────────┐
│ Year ┆ Unadjusted Business   ┆ Unadjusted            ┆ Adjusted Business ┆ Adjusted Depreciation │
│ ---  ┆ Profits               ┆ Depreciation Estima…  ┆ Profits           ┆ Estimate…             │
│ i64  ┆ ---                   ┆ ---                   ┆ ---               ┆ ---                   │
│      ┆ f64                   ┆ f64                   ┆ f64               ┆ f64                   │
╞══════╪═══════════════════════╪═══════════════════════╪═══════════════════╪═══════════════════════╡
│ 1929 ┆ 14.18                 ┆ 6.627                 ┆ 17.251            ┆ 3.556                 │
│ 1930 ┆ 9.252                 ┆ 6.66                  ┆ 12.334            ┆ 3.578                 │
│ 1931 ┆ 2.284                 ┆ 6.493                 ┆ 5.295             ┆ 3.482                 │
│ 1932 ┆ -3.177                ┆ 5.995                 ┆ -0.399            ┆ 3.217                 │
│ 1933 ┆ -3.31                 ┆ 5.612                 ┆ -0.709            ┆ 3.011                 │
│ …    ┆ …                     ┆ …                     ┆ …                 ┆ …                     │
│ 1935 ┆ 4.096                 ┆ 5.593                 ┆ 6.685             ┆ 3.004                 │
│ 1936 ┆ 6.55                  ┆ 5.616                 ┆ 9.148             ┆ 3.018                 │
│ 1937 ┆ 8.293                 ┆ 5.811                 ┆ 10.983            ┆ 3.121                 │
│ 1938 ┆ 5.869                 ┆ 5.836                 ┆ 8.569             ┆ 3.136                 │
│ 1939 ┆ 7.429                 ┆ 6.004                 ┆ 10.208            ┆ 3.225                 │
└──────┴───────────────────────┴───────────────────────┴───────────────────┴───────────────────────┘

In [14]:
#Creating a new variable derived from the information contained in the previously existing variables

#Please note that .with_column() has been deprecated; use .with_columns() instead

us_statistics = us_statistics.with_columns(
    (
        pl.col("Adjusted Business Profits")
        - pl.col("Adjusted Depreciation Estimates")
    ).alias("Net Economic Surplus")
)

print(us_statistics)

shape: (35, 6)
┌──────┬────────────┬──────────────┬───────────────────┬──────────────┬──────────────────────┐
│ Year ┆ Unadjusted ┆ Unadjusted   ┆ Adjusted Business ┆ Adjusted     ┆ Net Economic Surplus │
│ ---  ┆ Business   ┆ Depreciation ┆ Profits           ┆ Depreciation ┆ ---                  │
│ i64  ┆ Profits    ┆ Estima…      ┆ ---               ┆ Estimate…    ┆ f64                  │
│      ┆ ---        ┆ ---          ┆ f64               ┆ ---          ┆                      │
│      ┆ f64        ┆ f64          ┆                   ┆ f64          ┆                      │
╞══════╪════════════╪══════════════╪═══════════════════╪══════════════╪══════════════════════╡
│ 1929 ┆ 14.18      ┆ 6.627        ┆ 17.251            ┆ 3.556        ┆ 13.695               │
│ 1930 ┆ 9.252      ┆ 6.66         ┆ 12.334            ┆ 3.578        ┆ 8.756                │
│ 1931 ┆ 2.284      ┆ 6.493        ┆ 5.295             ┆ 3.482        ┆ 1.813                │
│ 1932 ┆ -3.177     ┆ 5.995        ┆ -0.399            ┆ 3.217        ┆ -3.616               │
│ 1933 ┆ -3.31      ┆ 5.612        ┆ -0.709            ┆ 3.011        ┆ -3.72                │
│ …    ┆ …          ┆ …            ┆ …                 ┆ …            ┆ …                    │
│ 1959 ┆ 40.686     ┆ 32.131       ┆ 58.895            ┆ 13.922       ┆ 44.973               │
│ 1960 ┆ 37.653     ┆ 33.577       ┆ 57.066            ┆ 14.164       ┆ 42.902               │
│ 1961 ┆ 37.374     ┆ 34.74        ┆ 57.758            ┆ 14.356       ┆ 43.402               │
│ 1962 ┆ 41.595     ┆ 38.366       ┆ 64.089            ┆ 15.872       ┆ 48.217               │
│ 1963 ┆ 42.929     ┆ 40.009       ┆ 66.558            ┆ 16.38        ┆ 50.178               │
└──────┴────────────┴──────────────┴───────────────────┴──────────────┴──────────────────────┘

In [15]:
#Renaming a column

us_statistics = us_statistics.rename({"Year": "Year of Data Analysis"})

print(us_statistics)

shape: (35, 6)
┌──────────────┬────────────┬─────────────────────────┬──────────┬──────────────┬──────────────┐
│ Year of Data ┆ Unadjusted ┆ Unadjusted Depreciation ┆ Adjusted ┆ Adjusted     ┆ Net Economic │
│ Analysis     ┆ Business   ┆ Estima…                 ┆ Business ┆ Depreciation ┆ Surplus      │
│ ---          ┆ Profits    ┆ ---                     ┆ Profits  ┆ Estimate…    ┆ ---          │
│ i64          ┆ ---        ┆ f64                     ┆ ---      ┆ ---          ┆ f64          │
│              ┆ f64        ┆                         ┆ f64      ┆ f64          ┆              │
╞══════════════╪════════════╪═════════════════════════╪══════════╪══════════════╪══════════════╡
│ 1929         ┆ 14.18      ┆ 6.627                   ┆ 17.251   ┆ 3.556        ┆ 13.695       │
│ 1930         ┆ 9.252      ┆ 6.66                    ┆ 12.334   ┆ 3.578        ┆ 8.756        │
│ 1931         ┆ 2.284      ┆ 6.493                   ┆ 5.295    ┆ 3.482        ┆ 1.813        │
│ 1932         ┆ -3.177     ┆ 5.995                   ┆ -0.399   ┆ 3.217        ┆ -3.616       │
│ 1933         ┆ -3.31      ┆ 5.612                   ┆ -0.709   ┆ 3.011        ┆ -3.72        │
│ …            ┆ …          ┆ …                       ┆ …        ┆ …            ┆ …            │
│ 1959         ┆ 40.686     ┆ 32.131                  ┆ 58.895   ┆ 13.922       ┆ 44.973       │
│ 1960         ┆ 37.653     ┆ 33.577                  ┆ 57.066   ┆ 14.164       ┆ 42.902       │
│ 1961         ┆ 37.374     ┆ 34.74                   ┆ 57.758   ┆ 14.356       ┆ 43.402       │
│ 1962         ┆ 41.595     ┆ 38.366                  ┆ 64.089   ┆ 15.872       ┆ 48.217       │
│ 1963         ┆ 42.929     ┆ 40.009                  ┆ 66.558   ┆ 16.38        ┆ 50.178       │
└──────────────┴────────────┴─────────────────────────┴──────────┴──────────────┴──────────────┘

In [16]:
#Calculating the mean

us_statistics.select([pl.mean("Net Economic Surplus").alias("mean"),])

shape: (1, 1)
┌───────────┐
│ mean      │
│ ---       │
│ f64       │
╞═══════════╡
│ 22.730429 │
└───────────┘

In [17]:
#Calculating the median

us_statistics.select([pl.mean("Net Economic Surplus").alias("median"),])

shape: (1, 1)
┌───────────┐
│ median    │
│ ---       │
│ f64       │
╞═══════════╡
│ 22.730429 │
└───────────┘

In [18]:
#Calculating aggregate statistics

us_statistics.describe()

shape: (9, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ Year of Data ┆ Unadjusted   ┆ Unadjusted  ┆ Adjusted    ┆ Adjusted    ┆ Net         │
│ ---        ┆ Analysis     ┆ Business     ┆ Depreciatio ┆ Business    ┆ Depreciatio ┆ Economic    │
│ str        ┆ ---          ┆ Profits      ┆ n Estima…   ┆ Profits     ┆ n Estimate… ┆ Surplus     │
│            ┆ f64          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│            ┆              ┆ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 35.0         ┆ 35.0         ┆ 35.0        ┆ 35.0        ┆ 35.0        ┆ 35.0        │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 1946.0       ┆ 22.181486    ┆ 15.272971   ┆ 30.092429   ┆ 7.362       ┆ 22.730429   │
│ std        ┆ 10.246951    ┆ 14.413577    ┆ 11.158541   ┆ 20.130741   ┆ 4.590121    ┆ 15.838768   │
│ min        ┆ 1929.0       ┆ -3.31        ┆ 5.531       ┆ -0.709      ┆ 2.967       ┆ -3.72       │
│ 25%        ┆ 1938.0       ┆ 9.252        ┆ 6.493       ┆ 12.334      ┆ 3.482       ┆ 8.756       │
│ 50%        ┆ 1946.0       ┆ 21.81        ┆ 9.334       ┆ 26.13       ┆ 5.014       ┆ 21.116      │
│ 75%        ┆ 1955.0       ┆ 35.695       ┆ 24.29       ┆ 49.683      ┆ 12.022      ┆ 36.144      │
│ max        ┆ 1963.0       ┆ 42.929       ┆ 40.009      ┆ 66.558      ┆ 16.38       ┆ 50.178      │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [19]:
#Sorting the data in ascending order by Unadjusted Business Profits

us_statistics.sort("Unadjusted Business Profits")

shape: (35, 6)
┌──────────────┬────────────┬─────────────────────────┬──────────┬──────────────┬──────────────┐
│ Year of Data ┆ Unadjusted ┆ Unadjusted Depreciation ┆ Adjusted ┆ Adjusted     ┆ Net Economic │
│ Analysis     ┆ Business   ┆ Estima…                 ┆ Business ┆ Depreciation ┆ Surplus      │
│ ---          ┆ Profits    ┆ ---                     ┆ Profits  ┆ Estimate…    ┆ ---          │
│ i64          ┆ ---        ┆ f64                     ┆ ---      ┆ ---          ┆ f64          │
│              ┆ f64        ┆                         ┆ f64      ┆ f64          ┆              │
╞══════════════╪════════════╪═════════════════════════╪══════════╪══════════════╪══════════════╡
│ 1933         ┆ -3.31      ┆ 5.612                   ┆ -0.709   ┆ 3.011        ┆ -3.72        │
│ 1932         ┆ -3.177     ┆ 5.995                   ┆ -0.399   ┆ 3.217        ┆ -3.616       │
│ 1934         ┆ 1.258      ┆ 5.531                   ┆ 3.822    ┆ 2.967        ┆ 0.855        │
│ 1931         ┆ 2.284      ┆ 6.493                   ┆ 5.295    ┆ 3.482        ┆ 1.813        │
│ 1935         ┆ 4.096      ┆ 5.593                   ┆ 6.685    ┆ 3.004        ┆ 3.681        │
│ …            ┆ …          ┆ …                       ┆ …        ┆ …            ┆ …            │
│ 1955         ┆ 37.55      ┆ 24.29                   ┆ 49.818   ┆ 12.022       ┆ 37.796       │
│ 1960         ┆ 37.653     ┆ 33.577                  ┆ 57.066   ┆ 14.164       ┆ 42.902       │
│ 1959         ┆ 40.686     ┆ 32.131                  ┆ 58.895   ┆ 13.922       ┆ 44.973       │
│ 1962         ┆ 41.595     ┆ 38.366                  ┆ 64.089   ┆ 15.872       ┆ 48.217       │
│ 1963         ┆ 42.929     ┆ 40.009                  ┆ 66.558   ┆ 16.38        ┆ 50.178       │
└──────────────┴────────────┴─────────────────────────┴──────────┴──────────────┴──────────────┘

In [20]:
#Sorting the data in descending order by Unadjusted Business Profits

us_statistics.sort("Unadjusted Business Profits", descending=True)

#Note that the correct command is descending=True, not reverse=True as in the Cheat Sheet

shape: (35, 6)
┌──────────────┬────────────┬─────────────────────────┬──────────┬──────────────┬──────────────┐
│ Year of Data ┆ Unadjusted ┆ Unadjusted Depreciation ┆ Adjusted ┆ Adjusted     ┆ Net Economic │
│ Analysis     ┆ Business   ┆ Estima…                 ┆ Business ┆ Depreciation ┆ Surplus      │
│ ---          ┆ Profits    ┆ ---                     ┆ Profits  ┆ Estimate…    ┆ ---          │
│ i64          ┆ ---        ┆ f64                     ┆ ---      ┆ ---          ┆ f64          │
│              ┆ f64        ┆                         ┆ f64      ┆ f64          ┆              │
╞══════════════╪════════════╪═════════════════════════╪══════════╪══════════════╪══════════════╡
│ 1963         ┆ 42.929     ┆ 40.009                  ┆ 66.558   ┆ 16.38        ┆ 50.178       │
│ 1962         ┆ 41.595     ┆ 38.366                  ┆ 64.089   ┆ 15.872       ┆ 48.217       │
│ 1959         ┆ 40.686     ┆ 32.131                  ┆ 58.895   ┆ 13.922       ┆ 44.973       │
│ 1960         ┆ 37.653     ┆ 33.577                  ┆ 57.066   ┆ 14.164       ┆ 42.902       │
│ 1955         ┆ 37.55      ┆ 24.29                   ┆ 49.818   ┆ 12.022       ┆ 37.796       │
│ …            ┆ …          ┆ …                       ┆ …        ┆ …            ┆ …            │
│ 1935         ┆ 4.096      ┆ 5.593                   ┆ 6.685    ┆ 3.004        ┆ 3.681        │
│ 1931         ┆ 2.284      ┆ 6.493                   ┆ 5.295    ┆ 3.482        ┆ 1.813        │
│ 1934         ┆ 1.258      ┆ 5.531                   ┆ 3.822    ┆ 2.967        ┆ 0.855        │
│ 1932         ┆ -3.177     ┆ 5.995                   ┆ -0.399   ┆ 3.217        ┆ -3.616       │
│ 1933         ┆ -3.31      ┆ 5.612                   ┆ -0.709   ┆ 3.011        ┆ -3.72        │
└──────────────┴────────────┴─────────────────────────┴──────────┴──────────────┴──────────────┘

In [21]:
#Wide to long format (using .inpivot)
#Please note that .melt has been deprecated

us_statistics_long = us_statistics.unpivot(
    on=["Unadjusted Business Profits", "Unadjusted Depreciation Estimates"],
    variable_name="Component",
    value_name="Value",
)

print(us_statistics_long)

#The opposite transformation can be done with .pivot()

shape: (70, 2)
┌─────────────────────────────────┬────────┐
│ Component                       ┆ Value  │
│ ---                             ┆ ---    │
│ str                             ┆ f64    │
╞═════════════════════════════════╪════════╡
│ Unadjusted Business Profits     ┆ 14.18  │
│ Unadjusted Business Profits     ┆ 9.252  │
│ Unadjusted Business Profits     ┆ 2.284  │
│ Unadjusted Business Profits     ┆ -3.177 │
│ Unadjusted Business Profits     ┆ -3.31  │
│ …                               ┆ …      │
│ Unadjusted Depreciation Estima… ┆ 32.131 │
│ Unadjusted Depreciation Estima… ┆ 33.577 │
│ Unadjusted Depreciation Estima… ┆ 34.74  │
│ Unadjusted Depreciation Estima… ┆ 38.366 │
│ Unadjusted Depreciation Estima… ┆ 40.009 │
└─────────────────────────────────┴────────┘

In [22]:
#Building a pipeline in Polars

(us_statistics
  .filter(pl.col("Year of Data Analysis") > 1945)
  .select(pl.col(["Year of Data Analysis", "Net Economic Surplus"]))
  .sort(pl.col("Net Economic Surplus"), descending=True)
  .slice(0, 5)
)

shape: (5, 2)
┌───────────────────────┬──────────────────────┐
│ Year of Data Analysis ┆ Net Economic Surplus │
│ ---                   ┆ ---                  │
│ i64                   ┆ f64                  │
╞═══════════════════════╪══════════════════════╡
│ 1963                  ┆ 50.178               │
│ 1962                  ┆ 48.217               │
│ 1959                  ┆ 44.973               │
│ 1961                  ┆ 43.402               │
│ 1960                  ┆ 42.902               │
└───────────────────────┴──────────────────────┘